#!/usr/bin/env node
// 数据库导入 / 方言转换 — 迁移到任意数据库的最后一公里
//
// 1) 恢复到 D1（本地或远程，标准 SQL dump）：
//      npm run db:import -- --sql backups/daohang-xxx.sql [--local]
//
// 2) 转换 JSON dump 为目标方言的 INSERT 脚本：
//      npm run db:import -- --data backups/daohang-xxx.json --to sqlite|pg|mysql --out import.sql
//    sqlite: sqlite3 new.db < import.sql
//    pg    : psql "$DATABASE_URL" -f import.sql   （表需先用 --to pg --schema 生成 DDL）
//    mysql : mysql < import.sql                   （同上）
import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

const arg = (name) => {
  const i = process.argv.indexOf(`--${name}`)
  return i > -1 ? process.argv[i + 1] : null
}
const DB = 'daohang'

// ---- 1) restore SQL dump into D1 ----
const sqlFile = arg('sql')
if (sqlFile) {
  const cmd = ['wrangler', 'd1', 'execute', DB, '--file', sqlFile, '-y']
  if (process.argv.includes('--local')) cmd.push('--local')
  console.log(`▶ Restoring ${sqlFile} into D1 (${process.argv.includes('--local') ? 'local' : 'remote'})`)
  execFileSync('npx', cmd, { stdio: 'inherit', shell: process.platform === 'win32' })
  console.log('✔ 恢复完成')
}

// ---- 2) JSON → dialect INSERT script ----
const dataFile = arg('data')
if (dataFile) {
  const to = arg('to') || 'sqlite'
  const out = arg('out') || `import-${to}.sql`
  const dump = JSON.parse(readFileSync(dataFile, 'utf8'))

  const q = {
    sqlite: (s) => `'${String(s).replace(/'/g, "''")}'`,
    pg: (s) => `'${String(s).replace(/'/g, "''")}'`,
    mysql: (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`,
  }[to]
  if (!q) { console.error('--to 仅支持 sqlite|pg|mysql'); process.exit(1) }

  const lit = (v) => v === null ? 'NULL' : typeof v === 'number' ? String(v) : q(v)

  const SCHEMA = {
    pg: [
      `CREATE TABLE IF NOT EXISTS nav_config (id INTEGER PRIMARY KEY CHECK (id = 1), config_json TEXT NOT NULL, updated_at TIMESTAMP DEFAULT NOW());`,
      `CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, email TEXT NOT NULL UNIQUE, pwd_hash TEXT NOT NULL, created_at TEXT NOT NULL);`,
      `CREATE TABLE IF NOT EXISTS sessions (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL, token_hash TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, expires_at TEXT NOT NULL);`,
      `CREATE TABLE IF NOT EXISTS user_data (user_id INTEGER NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (user_id, key));`,
      `CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);`,
      `CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);`,
    ],
    mysql: [
      "CREATE TABLE IF NOT EXISTS nav_config (id INTEGER PRIMARY KEY CHECK (id = 1), config_json LONGTEXT NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);",
      "CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTO_INCREMENT, email VARCHAR(255) NOT NULL UNIQUE, pwd_hash VARCHAR(255) NOT NULL, created_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
      "CREATE TABLE IF NOT EXISTS sessions (id INTEGER PRIMARY KEY AUTO_INCREMENT, user_id INTEGER NOT NULL, token_hash VARCHAR(64) NOT NULL UNIQUE, created_at VARCHAR(40) NOT NULL, expires_at VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
      "CREATE TABLE IF NOT EXISTS user_data (user_id INTEGER NOT NULL, `key` VARCHAR(64) NOT NULL, value LONGTEXT NOT NULL, updated_at VARCHAR(40) NOT NULL, PRIMARY KEY (user_id, `key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
      "CREATE INDEX idx_sessions_user ON sessions(user_id);",
      "CREATE INDEX idx_sessions_expiry ON sessions(expires_at);",
    ],
  }

  const lines = [`-- generated by db-import.mjs → ${to} @ ${new Date().toISOString()}`]
  if (SCHEMA[to]) lines.push('', '-- schema', ...SCHEMA[to], '')

  for (const [table, rows] of Object.entries(dump.tables || {})) {
    if (!rows.length) continue
    lines.push(`\n-- ${table} (${rows.length} rows)`)
    const cols = Object.keys(rows[0])
    for (const r of rows) {
      lines.push(`INSERT INTO ${to === 'mysql' && table === 'user_data' ? 'user_data (`key`, user_id, value, updated_at)' : table} (${cols.map(c => to === 'mysql' && c === 'key' ? '`key`' : c).join(', ')}) VALUES (${cols.map(c => lit(r[c])).join(', ')});`)
    }
  }
  writeFileSync(out, lines.join('\n') + '\n')
  console.log(`✔ 已生成 ${to} 方言脚本 → ${out}`)
}
